---
name: Export-Lexical
version: v0.0.4
author:
  - 'Chris Grau <cgrau@cpan.org>'
abstract: Lexically scoped subroutine imports
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
configure_requires:
  Module::Build: 0.35
provides:
  Export::Lexical:
    file: lib/Export/Lexical.pm
    version: v0.0.4
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
