---
name: Export-Lexical
version: 0.0.3
author:
  - 'Chris Grau <cgrau@cpan.org>'
abstract: Lexically scoped subroutine imports
license: perl
requires:
  version: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Export::Lexical:
    file: lib/Export/Lexical.pm
    version: 0.0.3
resources:
  license: http://dev.perl.org/licenses/
